# Generated by Django 3.2.7 on 2021-10-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211003_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='owner_name',
        ),
    ]
